{
 "title": "AirBook",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP requests",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logged users",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "users_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total 200 HTTP requests",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status_code=\"200\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 400 HTTP requests",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status_code=\"400\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 500 HTTP requests",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status_code=\"500\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (route_template) (http_requests_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  sum by (route_template) (http_request_duration_seconds_sum)\r\n  /\r\n  sum by (route_template) (http_request_duration_seconds_count)\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (route_template) (http_requests_total{status_code=~\"2..\"})\r\n  or\r\nsum by (route_template) (http_requests_total) * 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (route_template) (http_requests_total{status_code=~\"4..\"})\r\n  or\r\nsum by (route_template) (http_requests_total) * 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (route_template) (http_requests_total{status_code=~\"5..\"})\r\n  or\r\nsum by (route_template) (http_requests_total) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backend CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"backend\"} | json | level != \"\" [1m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level)(\r\n  count_over_time({job=\"backend\"} | json | level != \"\" [1m])\r\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend\"} |= ``"
    }
   ]
  }
 ]
}